export default  {
    nombreapp:"Maternidad",
    bebescte :[
            {
                id: "1",
                name: "EITHAN",
                motherName: "ROMERO MIRNA",
                motherDNI: "44370380",
                medicalRecordNumber: "HC 9483638",
                birthDate: "2024-09-13T21:54:00",
                admissionDate: "2024-09-13",
                gender: "masculino",
                gestationalAge: 30,
                weight: 695,
                status: "active",
            },
            {
                id: "2",
                name: "SAMUEL",
                motherName: "GONZALEZ LUCIA",
                motherDNI: "44274793",
                medicalRecordNumber: "HC 94856629",
                birthDate: "2024-10-29T10:00:00",
                admissionDate: "2024-10-29",
                gender: "masculino",
                gestationalAge: 24,
                weight: 625,
                status: "active",
            },
            {
                id: "3",
                name: "JAIRO",
                motherName: "DIAZ GISELA",
                motherDNI: "45484165",
                medicalRecordNumber: "HC 9495264",
                birthDate: "2024-09-23T14:30:00",
                admissionDate: "2024-09-23",
                gender: "masculino",
                gestationalAge: 31,
                weight: 910,
                status: "active",
            },
            {
                id: "4",
                name: "ALEX",
                motherName: "BARRERA MARIA",
                motherDNI: "35529768",
                medicalRecordNumber: "HC 9466461",
                birthDate: "2024-06-29T08:15:00",
                admissionDate: "2024-06-29",
                gender: "masculino",
                gestationalAge: 29,
                weight: 725,
                status: "discharged",
            },
            {
                id: "5",
                name: "JUSTINA",
                motherName: "VALDEZ PRISCILA",
                motherDNI: "44580265",
                medicalRecordNumber: "HC 9495208",
                birthDate: "2024-10-28T16:45:00",
                admissionDate: "2024-10-28",
                gender: "femenino",
                gestationalAge: 24,
                weight: 1348,
                status: "active",
            },
            {
                id: "6",
                name: "MARTINA",
                motherName: "VELEZ ERIKA",
                motherDNI: "36124432",
                medicalRecordNumber: "HC 9493562",
                birthDate: "2024-10-22T11:20:00",
                admissionDate: "2024-10-22",
                gender: "femenino",
                gestationalAge: 35,
                weight: 2360,
                status: "active",
            }
    ]
}