DUCTUS: SI NO 
        DUCTUS DAIGNOSTICO: ecografico clinico mixto
        DUCTUS TTO FARMACOLOGICO MED MED
        DUCTUS TTO QUIRURGICO SI NO
        CARDIOPATIA CONGENITA   SI NO
        DIAG CC: PRENATAL POSTNATAL