        PROTECTOR GASTRICO
        INHIBIDOR BOMBA H+
        PROBIOTICO
        ERITROMICINA
        FENTANILO
        MORFINA
        MIDAZOLAM
        PRECEDEX
        METADONA
        VECURONIO
        PROSTAGL